set -g history-limit 10000
set -s default-terminal "tmux-256color"
set -s escape-time 0

# remap prefix to space
set -g prefix c-space
unbind c-b
bind c-space send-prefix

# split windows using | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Move windows left and right
bind-key -r '<' swap-window -d -t '{previous}'
bind-key -r '>' swap-window -d -t '{next}'

# Automatically renumber windows when closing a pane
set-option -g renumber-windows on

set-option -g status-position top
set -g status-bg colour248

# Stay in copy mode on drag end.
unbind-key -T copy-mode-vi MouseDragEnd1Pane

set-option -w -g window-status-current-style bg=color115
set-option -ga pane-active-border-style fg=color115

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

# set-window-option -g mode-keys vi
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Use <prefix>C-l to clear screen
bind C-l send-keys 'C-l'

# Set highlight color
set-option -g mode-style bg=lightblue,fg=black
