version: 1
config:
  users:
    - first_name: Noah
      last_name: Moss
      password: test12345
      email: noah@metabase.com
    - first_name: Test
      last_name: Test
      password: test12345
      email: test@metabase.com
      login_attributes:
        id: 1
    - first_name: Test2
      last_name: Test2
      password: test12345
      email: test2@metabase.com
